title: Site

tabs:
  main:
    label: Content
    sections:
      content:
        type: pages
        parent: site.find("home")
  mail:
    label: Mail
    fields:
      mailSubject:
        label: Subject
        type: text
      mailContent:
        label: Content
        type: textarea
